//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Advent22.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Advent22.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6529
        ///8085
        ///4534
        ///1503
        ///2983
        ///5030
        ///2135
        ///5866
        ///5092
        ///5059
        ///1232
        ///
        ///15219
        ///7137
        ///2691
        ///2898
        ///1798
        ///
        ///4495
        ///2146
        ///3114
        ///5971
        ///2023
        ///2326
        ///6386
        ///4454
        ///2632
        ///3077
        ///2878
        ///2850
        ///
        ///8347
        ///4368
        ///2646
        ///3785
        ///8383
        ///1847
        ///10738
        ///4345
        ///
        ///1561
        ///5338
        ///3783
        ///4897
        ///3623
        ///6192
        ///2419
        ///6170
        ///1459
        ///1708
        ///4129
        ///4703
        ///3723
        ///5623
        ///
        ///4684
        ///4823
        ///1065
        ///2276
        ///
        ///5594
        ///2941
        ///3455
        ///3358
        ///4167
        ///4799
        ///3685
        ///3151
        ///3152
        ///1653
        ///5886
        ///5390
        ///1322
        ///
        ///5305
        ///3665
        ///1763
        ///3359
        ///1851
        ///2194
        ///7262
        ///5151
        ///6598
        ///6326
        ///3639
        ///
        ///7665
        ///4909
        ///5829
        ///6440
        ///77 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
    }
}
